#!/bin/bash

# Usage: put pinned-git in your PATH and alias git=pinned-git

GIT="$(type -p git)"
SELF="$(realpath "$(dirname "$0")")"

#export GIT_CURL_VERBOSE=1

# Absolutely necessary to avoid MITM with Apple-patched OpenSSL
# https://hynek.me/articles/apple-openssl-verification-surprises/
export OPENSSL_X509_TEA_DISABLE=1

pinned-git-clone() {
  local cert_name=$1
  shift
  exec "$GIT" "$cmd" --config "http.sslCAPath=$SELF/empty-dir" --config "http.sslCAInfo=$SELF/certs/${cert_name}.crt" "$@"
}

cmd="$1"
shift
if [[ "$cmd" == "clone" || "$cmd" == "cl" ]]; then
  if [[ "$*" == *https://github.com/* ]]; then
    pinned-git-clone github.com "$@"

  elif [[ "$*" == *https://gitlab.com/* ]]; then
    pinned-git-clone gitlab.com "$@"

  else
    exec "$GIT" "$cmd" "$@"
  fi
else
  exec "$GIT" "$cmd" "$@"
fi
