#!/bin/bash

set -eu

# Runs a pinned-git clone on every domain we have a pin for, to make sure
# the certificates are still up-to-date.

GIT="$PWD/bin/pinned-git"

cd "$(mktemp -d -t pinned-git-tests.XXXXXXXXXX)"

"$GIT" clone --depth=1 https://github.com/ludios/Desktopmagic
#"$GIT" clone           https://bitbucket.org/jcreenaune/svn-git-mirror
"$GIT" clone --depth=1 https://git.kernel.org/pub/scm/bluetooth/sbc.git
#"$GIT" clone           https://kernel.googlesource.com/pub/scm/bluetooth/sbc sbc-googlesource
#"$GIT" clone           https://chromium.googlesource.com/chromium/src/third_party/jsoncpp
#"$GIT" clone           https://android.googlesource.com/accessories/manifest
#"$GIT" clone           https://git.overlays.gentoo.org/gitroot/dev/remi.git
#"$GIT" clone           https://git.eclipse.org/gitroot/actf/org.eclipse.actf.visualization.releng.git
#"$GIT" clone           https://git.gnome.org/browse/clutter-box2dmm/
"$GIT" clone --depth=1 https://gitlab.com/gitlab-org/cookbook-gitlab.git
"$GIT" clone           https://anonscm.debian.org/git/letsencrypt/acme-tiny.git # note: sends bad packs with --depth=1
"$GIT" clone --depth=1 https://repo.or.cz/hg2git.git
#"$GIT" clone           https://alioth.debian.org/anonscm/git/pkg-perl/packages/libany-template-processdir-perl.git

# Make sure that ls-remote also gets pinned (ls-remote is used by yarn)
"$GIT" ls-remote --tags --heads https://github.com/torkelo/drop

# When called with no arguments, pinned-git should work like git,
# not return an error.
"$GIT" | grep "usage: git"
